import Footer from '@/app/layouts/Footer';
import type { Metadata } from 'next';
import { ThemeProvider } from './components/ThemeProvider';
import Header from './layouts/Header';
import './styles/index.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      {/* Emplacement des icons tout ce qui doit être dans la balise head */}
      <head></head>
      <body>
        <ThemeProvider attribute='class' defaultTheme='light' enableSystem>
          <Header />
          {children}
          {/* Emplacement du footer */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}

