import Footer from '@/layouts/Footer';
import Header from '@/layouts/Header';
import type { Metadata } from 'next';
import './styles/index.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      {/* Emplacement des icons tout ce qui doit être dans la balise head */}
      <head></head>
      <body>
        {/* Emplacement du header */}
        <Header />
        {children}
        <Footer />
        </body>
      {/* Emplacement du footer */}
    </html>
  );
}

